const ActionTypes = {
  LOADING: "LOADING",

  SEARCH_USERS_REQUEST_SUCCESS:'SEARCH_USERS_REQUEST_SUCCESS',
  SEARCH_USERS_REQUEST_FAILURE:'SEARCH_USERS_REQUEST_FAILURE',
  
  USER_LIST_REQUEST_FAILED: "USER_LIST_REQUEST_FAILED",
  USER_LIST_REQUEST_SUCCESS: "USER_LIST_REQUEST_SUCCESS",

  USER_DETAILS_REQUEST_FAILED: "USER_DETAILS_REQUEST_FAILED",
  USER_DETAILS_REQUEST_SUCCESS: "USER_DETAILS_REQUEST_SUCCESS",
};

export default ActionTypes;
